#!/usr/bin/env python3
"""
aeo-track — Schedule recurring aeo-baseline runs.

Generates a platform-appropriate scheduled job (launchd on macOS, cron on
Linux) that runs `aeo-baseline --yes` on a recurring cadence. By default it
prints what would be installed and asks the user to confirm with --apply.

Usage:
    # Dry-run (default): print the wrapper + plist/crontab without installing
    python3 track.py --install --schedule daily --baseline-script PATH

    # Apply the install
    python3 track.py --install --schedule daily --baseline-script PATH --apply

    # See current install state for this workspace
    python3 track.py --status

    # Remove a previously-installed schedule
    python3 track.py --remove --apply

State is tracked per workspace at ~/.aeo-track/<sha1(cwd)>/state.json so
multiple workspaces can be scheduled independently.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
import textwrap
from datetime import datetime, timezone

STATE_ROOT = os.path.expanduser("~/.aeo-track")
LAUNCHD_DIR = os.path.expanduser("~/Library/LaunchAgents")
LAUNCHD_LABEL_PREFIX = "ai.skills.aeo-track"
CRON_MARKER_PREFIX = "# aeo-track:"


# ── Workspace ID ────────────────────────────────────────────────────────────

def workspace_id(workdir: str) -> str:
    """Stable short ID for a workspace, derived from its absolute path."""
    abs_path = os.path.abspath(workdir)
    return hashlib.sha1(abs_path.encode()).hexdigest()[:12]


def state_dir(workdir: str) -> str:
    return os.path.join(STATE_ROOT, workspace_id(workdir))


def state_file(workdir: str) -> str:
    return os.path.join(state_dir(workdir), "state.json")


def load_state(workdir: str) -> dict | None:
    p = state_file(workdir)
    if not os.path.isfile(p):
        return None
    with open(p) as f:
        return json.load(f)


def write_state(workdir: str, state: dict) -> str:
    os.makedirs(state_dir(workdir), exist_ok=True)
    p = state_file(workdir)
    with open(p, "w") as f:
        json.dump(state, f, indent=2)
        f.write("\n")
    return p


def delete_state(workdir: str) -> None:
    d = state_dir(workdir)
    if os.path.isdir(d):
        shutil.rmtree(d)


# ── Schedule Parsing ───────────────────────────────────────────────────────

def parse_schedule(spec: str, hour: int = 9, minute: int = 0) -> dict:
    """Return a normalized schedule descriptor.

    Supports: "daily", "weekly" (Mon at given hour), "hourly", or "every Nm"
    (every N minutes — only useful for testing).
    """
    spec = spec.strip().lower()
    if spec == "daily":
        return {"kind": "daily", "hour": hour, "minute": minute}
    if spec == "weekly":
        return {"kind": "weekly", "weekday": 1, "hour": hour, "minute": minute}  # Mon
    if spec == "hourly":
        return {"kind": "hourly", "minute": minute}
    if spec.startswith("every "):
        rest = spec[6:].strip()
        if rest.endswith("m"):
            try:
                n = int(rest[:-1])
                if n < 1 or n > 59:
                    raise ValueError("minutes interval must be 1-59")
                return {"kind": "every_n_minutes", "minutes": n}
            except ValueError as e:
                raise ValueError(f"invalid 'every Nm' spec: {e}")
    raise ValueError(f"Unknown schedule {spec!r}. Supported: daily, weekly, hourly, 'every Nm'")


# ── Wrapper Script Generation ──────────────────────────────────────────────

WRAPPER_TEMPLATE = """#!/usr/bin/env bash
# Auto-generated by aeo-track. Edit only if you know what you're doing.
# Workspace: {workdir}
# Generated: {generated_at}
set -e
cd "{workdir}"
if [ -f .env ]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi
mkdir -p "{log_dir}"
exec python3 "{baseline_script}" --yes >> "{log_path}" 2>&1
"""


def generate_wrapper(workdir: str, baseline_script: str, state_dir_path: str) -> str:
    """Build the wrapper-script source that the scheduled job invokes."""
    log_dir = os.path.join(workdir, "aeo-data")
    log_path = os.path.join(log_dir, "aeo-track.log")
    return WRAPPER_TEMPLATE.format(
        workdir=workdir,
        baseline_script=baseline_script,
        log_dir=log_dir,
        log_path=log_path,
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    )


# ── launchd ────────────────────────────────────────────────────────────────

LAUNCHD_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>{label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>{wrapper_path}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>{workdir}</string>
  <key>StandardOutPath</key>
  <string>{log_path}</string>
  <key>StandardErrorPath</key>
  <string>{log_path}</string>
{schedule_block}
  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
"""


def launchd_schedule_block(schedule: dict) -> str:
    """XML fragment defining when the job runs."""
    if schedule["kind"] == "daily":
        return textwrap.dedent(f"""\
          <key>StartCalendarInterval</key>
          <dict>
            <key>Hour</key><integer>{schedule['hour']}</integer>
            <key>Minute</key><integer>{schedule['minute']}</integer>
          </dict>
        """)
    if schedule["kind"] == "weekly":
        return textwrap.dedent(f"""\
          <key>StartCalendarInterval</key>
          <dict>
            <key>Weekday</key><integer>{schedule['weekday']}</integer>
            <key>Hour</key><integer>{schedule['hour']}</integer>
            <key>Minute</key><integer>{schedule['minute']}</integer>
          </dict>
        """)
    if schedule["kind"] == "hourly":
        return textwrap.dedent(f"""\
          <key>StartCalendarInterval</key>
          <dict>
            <key>Minute</key><integer>{schedule['minute']}</integer>
          </dict>
        """)
    if schedule["kind"] == "every_n_minutes":
        seconds = schedule["minutes"] * 60
        return f"  <key>StartInterval</key>\n  <integer>{seconds}</integer>\n"
    raise ValueError(f"Unsupported schedule kind: {schedule['kind']}")


def launchd_label(workdir: str) -> str:
    return f"{LAUNCHD_LABEL_PREFIX}.{workspace_id(workdir)}"


def generate_launchd_plist(workdir: str, wrapper_path: str, schedule: dict) -> tuple[str, str]:
    """Return (target_plist_path, plist_xml_content)."""
    label = launchd_label(workdir)
    plist_path = os.path.join(LAUNCHD_DIR, f"{label}.plist")
    log_path = os.path.join(workdir, "aeo-data", "aeo-track.log")
    plist = LAUNCHD_TEMPLATE.format(
        label=label,
        wrapper_path=wrapper_path,
        workdir=workdir,
        log_path=log_path,
        schedule_block=launchd_schedule_block(schedule),
    )
    return plist_path, plist


# ── cron ───────────────────────────────────────────────────────────────────

def cron_schedule_field(schedule: dict) -> str:
    """Return the 5-field cron timing for the given schedule."""
    if schedule["kind"] == "daily":
        return f"{schedule['minute']} {schedule['hour']} * * *"
    if schedule["kind"] == "weekly":
        return f"{schedule['minute']} {schedule['hour']} * * {schedule['weekday']}"
    if schedule["kind"] == "hourly":
        return f"{schedule['minute']} * * * *"
    if schedule["kind"] == "every_n_minutes":
        return f"*/{schedule['minutes']} * * * *"
    raise ValueError(f"Unsupported schedule kind: {schedule['kind']}")


def cron_marker(workdir: str) -> str:
    return f"{CRON_MARKER_PREFIX} {workspace_id(workdir)}"


def generate_cron_line(workdir: str, wrapper_path: str, schedule: dict) -> str:
    """Build the crontab line — includes a marker comment for safe removal.

    `wrapper_path` is quoted so paths containing spaces still parse correctly.
    The trailing '# aeo-track: <id>' comment is ignored by cron but lets
    --remove safely strip just our workspace's lines.
    """
    timing = cron_schedule_field(schedule)
    return f'{timing} /bin/bash "{wrapper_path}"  {cron_marker(workdir)}\n'


# ── Apply / Remove ─────────────────────────────────────────────────────────

def apply_launchd(plist_path: str, plist_content: str) -> None:
    """Write the plist and load it. Idempotent: unload first if already loaded."""
    os.makedirs(os.path.dirname(plist_path), exist_ok=True)
    label = os.path.basename(plist_path).removesuffix(".plist")
    # If already loaded, unload first (idempotent install)
    subprocess.run(["launchctl", "unload", plist_path], capture_output=True)
    with open(plist_path, "w") as f:
        f.write(plist_content)
    result = subprocess.run(["launchctl", "load", plist_path], capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"launchctl load failed: {result.stderr.strip()}")


def remove_launchd(workdir: str) -> bool:
    """Unload + delete the plist if present. Returns True if anything removed."""
    label = launchd_label(workdir)
    plist_path = os.path.join(LAUNCHD_DIR, f"{label}.plist")
    if not os.path.isfile(plist_path):
        return False
    subprocess.run(["launchctl", "unload", plist_path], capture_output=True)
    os.unlink(plist_path)
    return True


def apply_cron(workdir: str, cron_line: str) -> None:
    """Append to crontab. Idempotent: removes any existing entry for this workspace first."""
    # Read existing crontab
    result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
    existing = result.stdout if result.returncode == 0 else ""
    marker = cron_marker(workdir)
    # Drop any lines for this workspace, then append the new one
    kept = [ln for ln in existing.splitlines(keepends=True) if marker not in ln]
    new_crontab = "".join(kept).rstrip("\n") + "\n" + cron_line
    proc = subprocess.run(["crontab", "-"], input=new_crontab, text=True, capture_output=True)
    if proc.returncode != 0:
        raise RuntimeError(f"crontab install failed: {proc.stderr.strip()}")


def remove_cron(workdir: str) -> bool:
    """Strip the workspace's line(s) from crontab. Returns True if anything removed."""
    result = subprocess.run(["crontab", "-l"], capture_output=True, text=True)
    if result.returncode != 0:
        return False
    existing = result.stdout
    marker = cron_marker(workdir)
    kept = [ln for ln in existing.splitlines(keepends=True) if marker not in ln]
    if len(kept) == len(existing.splitlines(keepends=True)):
        return False
    new_crontab = "".join(kept)
    proc = subprocess.run(["crontab", "-"], input=new_crontab, text=True, capture_output=True)
    if proc.returncode != 0:
        raise RuntimeError(f"crontab update failed: {proc.stderr.strip()}")
    return True


# ── Status ─────────────────────────────────────────────────────────────────

def status(workdir: str) -> int:
    state = load_state(workdir)
    if not state:
        print("No aeo-track schedule installed for this workspace.")
        return 1
    print(f"Workspace:       {state.get('workdir', workdir)}")
    print(f"Installed at:    {state.get('installed_at', 'unknown')}")
    print(f"Platform:        {state.get('platform', 'unknown')}")
    print(f"Schedule:        {state.get('schedule_spec', 'unknown')}")
    print(f"Wrapper script:  {state.get('wrapper_path', 'unknown')}")
    if state.get("platform") == "darwin":
        print(f"Plist:           {state.get('plist_path', 'unknown')}")
        # Show whether launchctl knows about it
        label = launchd_label(workdir)
        result = subprocess.run(["launchctl", "list", label], capture_output=True, text=True)
        if result.returncode == 0:
            print("Status:          loaded ✓")
        else:
            print("Status:          NOT loaded (run --install --apply to reinstall)")
    return 0


# ── Auto-detect baseline script ────────────────────────────────────────────

def find_baseline_script() -> str | None:
    """Look for aeo-baseline/scripts/baseline.py relative to this skill's parent.

    Returns absolute path or None.
    """
    here = os.path.dirname(os.path.abspath(__file__))
    candidates = [
        # When this skill is installed alongside aeo-baseline:
        os.path.join(here, "..", "..", "aeo-baseline", "scripts", "baseline.py"),
        # When inside the aeo-skills repo:
        os.path.join(here, "..", "..", "..", "aeo-baseline", "scripts", "baseline.py"),
    ]
    for c in candidates:
        c = os.path.normpath(c)
        if os.path.isfile(c):
            return c
    return None


# ── Main ──────────────────────────────────────────────────────────────────

def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Schedule recurring aeo-baseline runs.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    mode = p.add_mutually_exclusive_group()
    mode.add_argument("--install", action="store_true", help="Install a scheduled job (default action)")
    mode.add_argument("--remove", action="store_true", help="Remove a previously-installed schedule")
    mode.add_argument("--status", action="store_true", help="Show schedule info for the current workspace")

    p.add_argument("--workdir", default=None, help="Workspace dir (default: current directory)")
    p.add_argument("--baseline-script", default=None, help="Absolute path to aeo-baseline/scripts/baseline.py (auto-detected if omitted)")
    p.add_argument("--schedule", default="daily", help="daily | weekly | hourly | 'every Nm' (default: daily)")
    p.add_argument("--hour", type=int, default=9, help="Hour-of-day for daily/weekly (default: 9)")
    p.add_argument("--minute", type=int, default=0, help="Minute (default: 0)")
    p.add_argument("--apply", action="store_true", help="Actually install/remove (default is dry-run print)")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    workdir = os.path.abspath(args.workdir or os.getcwd())

    if args.status:
        return status(workdir)

    if args.remove:
        if not args.apply:
            print(f"Would remove aeo-track schedule for {workdir}")
            print("Run with --apply to actually remove.")
            return 0
        plat = platform.system().lower()
        removed_any = False
        if plat == "darwin":
            removed_any = remove_launchd(workdir)
        elif plat == "linux":
            removed_any = remove_cron(workdir)
        delete_state(workdir)
        print("✓ Removed." if removed_any else "Nothing to remove.")
        return 0

    # Default: --install
    if not os.path.isfile(os.path.join(workdir, "aeo.config.json")):
        print(f"✗ No aeo.config.json in {workdir}. Run aeo-init first.", file=sys.stderr)
        return 2

    baseline_script = args.baseline_script or find_baseline_script()
    if not baseline_script:
        print("✗ Could not locate aeo-baseline/scripts/baseline.py. Pass --baseline-script PATH.", file=sys.stderr)
        return 2
    baseline_script = os.path.abspath(baseline_script)
    if not os.path.isfile(baseline_script):
        print(f"✗ Baseline script not found: {baseline_script}", file=sys.stderr)
        return 2

    try:
        schedule = parse_schedule(args.schedule, hour=args.hour, minute=args.minute)
    except ValueError as e:
        print(f"✗ {e}", file=sys.stderr)
        return 1

    # Generate wrapper script
    sd = state_dir(workdir)
    wrapper_path = os.path.join(sd, "run.sh")
    wrapper = generate_wrapper(workdir, baseline_script, sd)

    plat = platform.system().lower()
    print(f"Platform:        {plat}")
    print(f"Workspace:       {workdir}")
    print(f"Baseline script: {baseline_script}")
    print(f"Schedule:        {schedule}")
    print(f"Wrapper:         {wrapper_path}")

    if plat == "darwin":
        plist_path, plist_content = generate_launchd_plist(workdir, wrapper_path, schedule)
        print(f"\n── Wrapper script ({wrapper_path}) ──")
        print(wrapper)
        print(f"── Plist ({plist_path}) ──")
        print(plist_content)
        if not args.apply:
            print("Run with --apply to install.")
            return 0
        os.makedirs(sd, exist_ok=True)
        with open(wrapper_path, "w") as f:
            f.write(wrapper)
        os.chmod(wrapper_path, 0o755)
        apply_launchd(plist_path, plist_content)
        state = {
            "workdir": workdir,
            "platform": "darwin",
            "schedule_spec": args.schedule,
            "schedule_resolved": schedule,
            "wrapper_path": wrapper_path,
            "plist_path": plist_path,
            "baseline_script": baseline_script,
            "installed_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        }
        write_state(workdir, state)
        print(f"✓ Installed launchd job '{launchd_label(workdir)}'.")
        return 0

    if plat == "linux":
        cron_line = generate_cron_line(workdir, wrapper_path, schedule)
        print(f"\n── Wrapper script ({wrapper_path}) ──")
        print(wrapper)
        print(f"── Crontab line ──")
        print(cron_line.strip())
        if not args.apply:
            print("\nRun with --apply to install.")
            return 0
        os.makedirs(sd, exist_ok=True)
        with open(wrapper_path, "w") as f:
            f.write(wrapper)
        os.chmod(wrapper_path, 0o755)
        apply_cron(workdir, cron_line)
        state = {
            "workdir": workdir,
            "platform": "linux",
            "schedule_spec": args.schedule,
            "schedule_resolved": schedule,
            "wrapper_path": wrapper_path,
            "cron_line": cron_line.strip(),
            "baseline_script": baseline_script,
            "installed_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        }
        write_state(workdir, state)
        print(f"✓ Installed crontab entry for workspace {workspace_id(workdir)}.")
        return 0

    print(f"✗ Platform {plat!r} not supported for automated install.", file=sys.stderr)
    print(f"  Generated wrapper script and schedule descriptor:")
    print(f"  Wrapper:  {wrapper_path}")
    print(f"  Schedule: {schedule}")
    print(f"  Wire this into Task Scheduler / your scheduler of choice manually.")
    return 3


if __name__ == "__main__":
    sys.exit(main())
